services:
  terraform:
    image: hashicorp/terraform:1.8.4
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_DEFAULT_REGION=ap-southeast-1
      - TF_WORKSPACE=${TF_WORKSPACE}
      - TF_VAR_db_password=${TF_VAR_db_password}
      # - TF_VAR_ecr_proxy_image=${TF_VAR_ecr_proxy_image}
      - TF_VAR_ecr_api_sys_image=${TF_VAR_ecr_api_sys_image}
      - TF_VAR_ecr_api_app_image=${TF_VAR_ecr_api_app_image}
      - TF_VAR_ecr_report_image=${TF_VAR_ecr_report_image}
